### ISSUE TITLE
Missing register.php source file

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#44]
Hey Tach-Yon,  I just got back and tried this again and I must say this is really a big improvement. The only issue that I found out so far is this missing file to actually register the user to the database:

https://github.com/Tach-Yon/Tap-Tap-Adventure/blob/master/server/js/controllers/incoming.js#L145

**Comment by Tach-Yon** [comment]
The register.php is part of my modifications to the API to fit with NodeBB. I am not sure if anyone really wants to use the same database, so I left it up to anyone who wants to modify it. It's not even necessary, you can simply install NodeBB, get the `nodebb-write-api` plugin and simply use the POST to that link instead of having a php file do it. The one thing I will say is that if you do use this method, use my version of the `write-api` as it fixes the issue where multiple users can be signed in.

https://github.com/Tach-Yon/nodebb-plugin-write-api

**Comment by wini3d** [comment]
I see. So is there a quick guide or documentation on how this should work or hook up? Maybe have this new plugin as an example and reflect with the changes on that part of code instead of the php version? Adding the process on the readme would help too.

Thanks again.

**Comment by wini3d** [comment]
or you can just remove the code or make it optional. The thing is I'm trying to simulate a user registration and always getting errors pointing to this part. I'm sure first time users will stumble on this part as well.

**Comment by Tach-Yon** [comment]
I'm sorry, but this repository holds the code exactly as it is posted on TTA. The registration API is pretty straight forward. Either POST or GET from whatever API you desire, and pass the data onto the rest. I will do a documentation of how the entire `handleIntro` function works, but not sometime soon.

**Comment by wini3d** [comment]
Ok thanks and I get it. So the end user register part has a default NodeBB api hook and for other preference, just modify as it is.

> I will do a documentation of how the entire handleIntro function works, but not sometime soon.

That would be much appreciated.

issue solved.
