### ISSUE TITLE
Drop/Equip item

### ISSUE THREAD

**Issue by tanguyfalconnet** [Tach-Yon/Tap-Tap-Adventure#67]
Hi,

I have some problem in game with dropping items (and equip or use).

When I try to drop an item (sword, helmet,...) nothing happen. When I use a potion, the potion counter is not decremented. And when I want to equip an item, this item is replicated in my inventory, so right now my inventory is fulll ^^

I appreciate any help that you can provide. With some elements I can modify the source code directly.

**Comment by Mixone-FinallyHere** [comment]
In `player.js` int the functions `setArmour`, `setWeapon`, etc...
Shouldn't there be a `self.inventory.removeItem(id)` or something similar?

**Comment by Tach-Yon** [comment]
@Mixone-FinallyHere There is, except the `inventory` has a superclass of `container`. The item is first passed through the `inventory` subclass and the superclass removes the item itself from the container. After which the `inventory` will pass a packet to the client in order to let surrounding people know there's been an item dropped.
